## Assignment 2
## Name: Sagar Santra
## Reg. No. : 24-14-17
## Course: Modelling And Simulation

### Q1

### a) Create a variable named var1 that stores an array of numbers from 0 to 30,inclusive. Print var1 and its shape. Hint : arange
### b) Change var2 to a validly-shaped two-dimensional matrix and store it in a new variable called var2. Print var2 and its shape. Hint: Use the reshape function
### c) Create a third variable, var3 that reshapes it into a valid three-dimensional shape.Print var3 and its shape.
### d) Use two-dimensional array indexing to set the first value in the second row of var2 to -1. Now look at var1 and var3. Did they change? Explain what’s going on. (Hint: does reshape return a view or a copy?)
### e) Another thing that comes up a lot with array shapes is thinking about how to aggregate over specific dimensions. Figure out how the NumPy sum function works (and the axis argument in particular) and do the following:
(i) Sum var3 over its second dimension and print the result.
(ii) Sum var3 over its third dimension and print the result.
(iii) Sum var3 over both its first and third dimensions and print the result.
### f) Write code to do the following:
(i) Slice out the second row of var2 and print it.
(ii) Slice out the last column of var2 using the -1 notation and print it.
(iii) Slice out the top right 2 × 2 submatrix of var2 and print it.

In [2]:
import numpy as np
var1=np.arange(31)
print(var1)
print("Shape of Var1:",var1.shape)
print("Dimension of Var1:",var1.ndim)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
Shape of Var1: (31,)
Dimension of Var1: 1


In [3]:
new_array=np.delete(var1,0)
var2=new_array.reshape(2,-1)
print("var2")
print(var2)
print("Shape of Var2:",var2.shape)
print("Dimension of Var2:",var2.ndim)

var2
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]]
Shape of Var2: (2, 15)
Dimension of Var2: 2


In [4]:
var3=var2.reshape(var2.shape[0],-1,var2.shape[1])
print("var3")
print(var3)
print("Shape of Var3:",var3.shape)
print("Dimension of Var3:",var3.ndim)

var3
[[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]

 [[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]]]
Shape of Var3: (2, 1, 15)
Dimension of Var3: 3


In [5]:
var2[1,0]=-1
print("\nModified var2 after setting the first value in the second row to -1:")
print(var2)
print("var1",var1)
print("var3",var3)


Modified var2 after setting the first value in the second row to -1:
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [-1 17 18 19 20 21 22 23 24 25 26 27 28 29 30]]
var1 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
var3 [[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]

 [[-1 17 18 19 20 21 22 23 24 25 26 27 28 29 30]]]


In [6]:
sum_second = np.sum(var3, axis=1)
print("Sum over the second dimension:\n", sum_second)


Sum over the second dimension:
 [[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [-1 17 18 19 20 21 22 23 24 25 26 27 28 29 30]]


In [7]:
sum_third= np.sum(var3, axis=2)
print("Sum over the second dimension:\n", sum_third)


Sum over the second dimension:
 [[120]
 [328]]


In [27]:
sum_fist_third= np.sum(var3, axis=(0,2))
print("Sum over the second dimension:\n", sum_fist_third)

Sum over the second dimension:
 [448]


In [8]:
print("var2")
print(var2)
print("Second Row is :",var2[1:2])

var2
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [-1 17 18 19 20 21 22 23 24 25 26 27 28 29 30]]
Second Row is : [[-1 17 18 19 20 21 22 23 24 25 26 27 28 29 30]]


In [9]:
print("Last Column of var2 is:")
print(var2[ :,-1:])

Last Column of var2 is:
[[15]
 [30]]


In [10]:
print("The top right 2x2 matrix is :")
print(var2[0:2,13:])

The top right 2x2 matrix is :
[[14 15]
 [29 30]]


### Q2

## a) The most basic kind of broadcast is with a scalar, in which you can perform a binary operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to perform that operation with the scalar for every element of the array. To try this out, create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function.
## b) Now, create a 10 × 10 matrix A in which Ai j = i + j. You’ll be able to do this using the vector you just created, and adding it to a reshaped version of itself.
## c) A very common use of broadcasting is to standardize data, i.e., to make it have zero mean and unit variance. First, create a fake “data set” with 50 examples,each with five dimensions.
## import numpy.random as npr
## data = np.exp(npr.randn ( 50 , 5 ) )
## d) You don’t worry too much about what this code is doing at this stage of the course, but for completeness: it imports the NumPy random number generation library, then generates a 50 × 5 matrix of standard normal
## e) Now, compute the mean and standard deviation of each column. This should result in two vectors of length 5. You’ll need to think a little bit about how to use the axis argument to mean and std. Store these vectors into variables and print both of them.
## f) Now standardize the data matrix by 1) subtracting the mean off of each column,and 2) dividing each column by its standard deviation. Do this via broadcasting,and store the result in a matrix called normalized. To verify that you successfullydid it, compute the mean and standard deviation ofthe columns of normalized and print them out.


In [11]:
vector=np.arange(0,10)
vector+=1
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
A=vector[:,np.newaxis]+vector
print("The required 10x10 matrix is")
print("A=")
print(A)

The required 10x10 matrix is
A=
[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


In [13]:
import numpy.random as npr
data = np.exp(npr.randn ( 50 , 5 ) )
print(data)

[[ 0.33993817  0.30915866  0.5716007   0.2731089   2.29491176]
 [ 3.84809843  0.57759076  2.29956969  3.75107982  0.08510464]
 [ 1.30719762  2.74977958  1.16025764  2.13067655  5.70980569]
 [ 1.01722142  1.29337725  1.61535638  0.3444222   3.36648871]
 [ 0.34785728  0.78894805  3.14404954  0.97301919  0.97406954]
 [ 1.57429951  0.30414943  1.02778999  1.79668546  0.98041046]
 [ 2.64939687  1.2074581   1.17940029  0.57524055  0.73671741]
 [ 1.47150295  7.80145902  0.1293597   0.30647409  2.95388834]
 [ 0.04085523  2.11970838  1.29399846  1.00567268  0.33637585]
 [ 0.71048532  2.00252373  1.01977477  0.5179186   0.80747904]
 [ 1.04932511  0.58863184  8.43492051  4.53664239  0.8586704 ]
 [ 0.67774361  0.63425675  0.56710567  1.02221031  0.59913518]
 [ 0.76135937  1.79861329  5.41578661  0.81708122  0.35108102]
 [ 0.45483449  0.31132533  1.1654289   0.59837608  0.31341208]
 [ 1.3187512   1.03966362  1.90652651  0.34237939  1.74596056]
 [ 1.25335223  0.35186093  2.29234183  0.97711321  0.73

In [14]:

data = np.random.normal(size=(50, 5))
log_normal_data = np.exp(data)
mean_vector = np.mean(log_normal_data, axis=0)
std_vector = np.std(log_normal_data, axis=0)
print("Mean of each column:", mean_vector)
print("Standard deviation of each column:", std_vector)


Mean of each column: [2.43704959 1.75716744 1.90721006 1.23577953 1.29555199]
Standard deviation of each column: [3.24547466 2.08846286 1.94543991 1.46034244 1.34453848]


In [15]:
data = np.random.normal(size=(50, 5))
log_normal_data = np.exp(data)
mean_vector = np.mean(log_normal_data, axis=0)
std_vector = np.std(log_normal_data, axis=0)
normalized = (log_normal_data - mean_vector) / std_vector
normalized_mean = np.mean(normalized, axis=0)
normalized_std = np.std(normalized, axis=0)
print("Mean of each column in normalized data:", normalized_mean)
print("Standard deviation of each column in normalized data:", normalized_std)

Mean of each column in normalized data: [ 1.33226763e-16 -5.24025268e-16 -2.04281037e-16  3.61932706e-16
  4.10782519e-17]
Standard deviation of each column in normalized data: [1. 1. 1. 1. 1.]


### Q3
## a) A Vandermonde matrix is a matrix generated from a vector in which each column of the matrix is an integer power starting from zero. So, if I have a column vector [x1, x2, . . . , xN]T , then the associated (square) Vandermonde matrix would be Use what you learned about broadcasting in the previous problem to write a function that will produce a Vandermonde matrix for a vector [1, 2, . . . ,N]T for any N. Do it without using a loop. Here’s a stub to get you started:
## def vandermonde (N):
## vec = np.arange (N) +1
 # write your code here .
## Use your function for N = 12, store it in variable named vander, and print the result.
## b) Now, let’s make a pretend linear system problem with this matrix. Create a vector of all ones, of length 12 and call it x. Perform a matrix-vector multiplication of vander with the vector you just created and store that in a new vector and call it b. Print the vector b.
## c) First, solve the linear system the naïve way, pretending like you don’t know x. Import numpy.linalg, invert V and multiply it by b. Print out your result. What should you get for your answer? If the answer is different than what you expected, write a sentence about that difference.
## d) Now, solve the same linear system using solve. Print out the result. Does it seem more or less in line with what you’d expect?

In [16]:
def vandermonde(N):
    vec = np.arange(N) + 1
    return vec[:, None] ** np.arange(N)
vander = vandermonde(12)
print(vander)

[[           1            1            1            1            1
             1            1            1            1            1
             1            1]
 [           1            2            4            8           16
            32           64          128          256          512
          1024         2048]
 [           1            3            9           27           81
           243          729         2187         6561        19683
         59049       177147]
 [           1            4           16           64          256
          1024         4096        16384        65536       262144
       1048576      4194304]
 [           1            5           25          125          625
          3125        15625        78125       390625      1953125
       9765625     48828125]
 [           1            6           36          216         1296
          7776        46656       279936      1679616     10077696
      60466176    362797056]
 [           1        

In [18]:
import numpy as np
N = 12
x = np.ones(N)
print(x)
b = np.dot(vander,x)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 9.81706810e+09
 3.53036921e+10 1.11111111e+11 3.13842838e+11 8.10554586e+11]


In [19]:
from numpy.linalg import inv
x_estimated =np.dot(inv(vander),b)
print(x_estimated)

[-12.26953125   5.90625     15.421875    -6.03515625   2.05859375
   0.92675781   1.00244141   1.00010681   0.99997711   1.00000131
   0.99999996   1.        ]


In [26]:
x_solved = np.linalg.solve(vander, b)
print(x_solved)

[0.98080503 1.05139768 0.94513807 1.03151945 0.98899166 1.00248816
 0.99962407 1.0000384  0.99999737 1.00000012 1.         1.        ]
